
import React, { useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Separator } from '../components/ui/separator';

export function Terms() {
  useEffect(() => {
    // SEO optimization
    document.title = 'Terms of Service - MatrixProg | AI Education Platform Terms';
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'MatrixProg terms of service - User agreement for our AI-powered education platform. Fair usage policies for students and educators.');
    } else {
      const meta = document.createElement('meta');
      meta.name = 'description';
      meta.content = 'MatrixProg terms of service - User agreement for our AI-powered education platform. Fair usage policies for students and educators.';
      document.head.appendChild(meta);
    }

    // Add structured data for SEO
    const structuredData = {
      "@context": "https://schema.org",
      "@type": "WebPage",
      "name": "Terms of Service",
      "description": "MatrixProg terms of service and user agreement",
      "url": "https://matrixprog.com/terms",
      "isPartOf": {
        "@type": "WebSite",
        "name": "MatrixProg",
        "url": "https://matrixprog.com"
      }
    };

    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.textContent = JSON.stringify(structuredData);
    document.head.appendChild(script);

    return () => {
      const existingScript = document.querySelector('script[type="application/ld+json"]');
      if (existingScript) {
        document.head.removeChild(existingScript);
      }
    };
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <Card className="shadow-xl">
          <CardHeader className="text-center">
            <CardTitle className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</CardTitle>
            <p className="text-gray-600">Last updated: January 2, 2025</p>
          </CardHeader>
          <CardContent className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700 mb-4">
                By accessing or using MatrixProg, you agree to be bound by these Terms of Service and our Privacy Policy. 
                If you do not agree to these terms, please do not use our platform.
              </p>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-700 mb-4">
                MatrixProg is an AI-powered education platform offering:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Personalized learning roadmaps generated by AI</li>
                <li>Interactive AI tutoring and chat support</li>
                <li>Skill assessments and progress tracking</li>
                <li>Gamified learning experiences with quests and achievements</li>
                <li>Study planning and scheduling tools</li>
                <li>Coding challenges and practice environments</li>
              </ul>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Accounts and Eligibility</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Account Creation</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>You must provide accurate and complete information</li>
                    <li>You are responsible for maintaining account security</li>
                    <li>One account per person is allowed</li>
                    <li>You must notify us of unauthorized account access</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Age Requirements</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Users under 13 require parental consent (COPPA compliance)</li>
                    <li>Users 13-17 should have parental supervision</li>
                    <li>Adults 18+ can create accounts independently</li>
                  </ul>
                </div>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Subscription Plans and Payments</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Plan Types</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li><strong>Free:</strong> Limited features and usage quotas</li>
                    <li><strong>Pro ($14.99/month):</strong> Unlimited AI tutoring and advanced features</li>
                    <li><strong>Elite ($24.99/month):</strong> Premium features and priority support</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Payment Terms</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Subscriptions are billed monthly unless cancelled</li>
                    <li>Payments processed securely through Paddle</li>
                    <li>Refunds available within 30 days of purchase</li>
                    <li>Price changes require 30 days advance notice</li>
                  </ul>
                </div>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Acceptable Use Policy</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Permitted Uses</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Educational and learning purposes</li>
                    <li>Personal skill development</li>
                    <li>Classroom and institutional use (with appropriate license)</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Prohibited Activities</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Sharing account credentials with others</li>
                    <li>Reverse engineering or attempting to access source code</li>
                    <li>Using the platform for commercial purposes without authorization</li>
                    <li>Submitting harmful, offensive, or inappropriate content</li>
                    <li>Attempting to circumvent usage limits or security measures</li>
                    <li>Using automated tools to access the platform</li>
                  </ul>
                </div>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Intellectual Property</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Our Content</h3>
                  <p className="text-gray-700 mb-2">
                    MatrixProg owns all rights to the platform, including:
                  </p>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Software, algorithms, and AI models</li>
                    <li>Educational content and assessments</li>
                    <li>Trademarks, logos, and branding</li>
                    <li>User interface and design elements</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Your Content</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>You retain ownership of content you create</li>
                    <li>You grant us license to use your content for platform improvement</li>
                    <li>You're responsible for ensuring you have rights to submitted content</li>
                  </ul>
                </div>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Privacy and Data Protection</h2>
              <p className="text-gray-700 mb-4">
                Your privacy is important to us. Please review our Privacy Policy to understand how we collect, 
                use, and protect your information. By using MatrixProg, you consent to our data practices 
                as described in the Privacy Policy.
              </p>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Disclaimers and Limitations</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Service Availability</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>Platform provided "as is" without warranties</li>
                    <li>We don't guarantee continuous, error-free operation</li>
                    <li>Scheduled maintenance may cause temporary disruptions</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">Educational Content</h3>
                  <ul className="list-disc pl-6 text-gray-700 space-y-2">
                    <li>AI-generated content may contain inaccuracies</li>
                    <li>Content is for educational purposes, not professional advice</li>
                    <li>Users should verify important information independently</li>
                  </ul>
                </div>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Termination</h2>
              <div className="space-y-4">
                <p className="text-gray-700">
                  Either party may terminate this agreement:
                </p>
                <ul className="list-disc pl-6 text-gray-700 space-y-2">
                  <li>You may cancel your account at any time</li>
                  <li>We may suspend or terminate accounts for violations</li>
                  <li>Termination doesn't excuse payment obligations</li>
                  <li>We'll provide reasonable notice for non-breach terminations</li>
                </ul>
              </div>
            </section>

            <Separator className="my-6" />

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Contact Information</h2>
              <p className="text-gray-700 mb-4">
                For questions about these terms, contact us:
              </p>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">
                  <strong>Email:</strong> legal@matrixprog.com<br />
                  <strong>Support:</strong> support@matrixprog.com<br />
                  <strong>Address:</strong> MatrixProg Legal Team<br />
                  <strong>Response Time:</strong> Within 48 hours for urgent matters
                </p>
              </div>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
